--Oracle's image will run any .sql files
-- mount into /docker-entrypoint-initdb.d on first startup
BEGIN
   EXECUTE IMMEDIATE 'DROP USER py_app CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      -- ORA-01918: user does not exist
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/

create user py_app identified by py_app_password
    default tablespace users
    temporary tablespace temp;

-- Allow it to connect and create most objects
grant connect, resource to py_app;

-- Without an explicit quota, the user can’t allocate any space
alter user py_app
    quota unlimited on users;

-- (Optional) Switch the session default schema right away
alter session set current_schema = py_app;

create table users (
    id            number
        generated by default as identity
    primary key,
    username      varchar2(50) unique not null,
    password_hash varchar2(256) not null,
    created_at    timestamp default systimestamp
);

create table logs (
    id        number
        generated by default as identity
    primary key,
    username   varchar2(100) not null,
    endpoint    varchar2(100) not null,
    timestamp timestamp default systimestamp
);