--Oracle's image will run any .sql files
-- mount into /docker-entrypoint-initdb.d on first startup

create user py_app identified by ${ORACLE_PASSWORD}
    default tablespace users
    temporary tablespace temp;

-- Allow it to connect and create most objects
grant connect,resource to py_app;

-- Without an explicit quota, the user can’t allocate any space
alter user py_app
    quota unlimited on users;

-- (Optional) Switch the session default schema right away
alter session set current_schema = py_app;

create table users (
    id            number
        generated by default as identity
    primary key,
    username      varchar2(50) unique not null,
    password_hash varchar2(256) not null,
    created_at    timestamp default systimestamp
);

create table logs (
    id        number
        generated by default as identity
    primary key,
    user_id   number
        references users ( id ),
    action    varchar2(100) not null,
    timestamp timestamp default systimestamp
);